# Generated by Django 2.1.4 on 2018-12-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='average_consumption',
            field=models.FloatField(default=0.0),
        ),
    ]
