# Generated by Django 2.1.4 on 2018-12-10 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displug', '0002_devices_average_consumption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='average_consumption',
            new_name='monthly_consumption',
        ),
    ]
